apiVersion: v1
kind: Service
metadata:
  name: {{ include "boxy.fullname" . }}-ctrl-headless
  namespace: {{ include "boxy.sandboxNamespace" . }}
  labels:
    app: boxy-controller
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: boxy-controller
  ports:
    - name: http
      port: {{ .Values.controllerPort }}
      targetPort: http
