{{- if not .Values.mtlsDisabled }}
{{- $ca := genCA .Values.mtlsCACN 3650 }}
{{- $serverCert := genSignedCert .Values.mtlsServerCN nil nil 3650 $ca }}
{{- $clientCert := genSignedCert .Values.mtlsClientCN nil nil 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: boxy-mtls-controller
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $serverCert.Cert | b64enc | quote }}
  tls.key: {{ $serverCert.Key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: boxy-mtls-router
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $clientCert.Cert | b64enc | quote }}
  tls.key: {{ $clientCert.Key | b64enc | quote }}
{{- end }}
