{{- if not .Values.mtls.disabled }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace "boxy-mtls-controller" }}
{{- if not $existing }}
{{- $ca := genCA .Values.mtls.caCN 3650 }}
{{- $serverDNS := list .Values.mtls.serverCN (printf "*.boxy-ctrl-headless.%s.svc" .Release.Namespace) (printf "*.boxy-ctrl-headless.%s.svc.cluster.local" .Release.Namespace) }}
{{- $serverCert := genSignedCert .Values.mtls.serverCN nil $serverDNS 3650 $ca }}
{{- $clientDNS := list .Values.mtls.clientCN }}
{{- $clientCert := genSignedCert .Values.mtls.clientCN nil $clientDNS 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: boxy-mtls-controller
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $serverCert.Cert | b64enc | quote }}
  tls.key: {{ $serverCert.Key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: boxy-mtls-router
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $clientCert.Cert | b64enc | quote }}
  tls.key: {{ $clientCert.Key | b64enc | quote }}
{{- end }}
{{- end }}
