apiVersion: v1
kind: Service
metadata:
  name: {{ include "boxy.fullname" . }}-router
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: boxy-router
  ports:
    - name: http
      port: {{ .Values.router.servicePort }}
      targetPort: http
