{{- if .Values.router.auth.staticToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boxy.fullname" . }}-tokens
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  router-token: {{ .Values.router.auth.staticToken | quote }}
{{- end }}
