{{- if or .Values.router.auth.staticToken .Values.controller.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boxy.fullname" . }}-tokens
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if .Values.router.auth.staticToken }}
  router-token: {{ .Values.router.auth.staticToken | quote }}
  {{- end }}
  {{- if .Values.controller.token }}
  controller-token: {{ .Values.controller.token | quote }}
  {{- end }}
{{- end }}
