apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.router.serviceAccount }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccount }}
  namespace: {{ include "boxy.sandboxNamespace" . }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.serviceAccount }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
