apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.routerServiceAccount }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workerServiceAccount }}
  namespace: {{ include "boxy.sandboxNamespace" . }}
automountServiceAccountToken: false
