//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"

	"boxy.dev/boxy/internal/api"
)

func (in *Sandbox) DeepCopyInto(out *Sandbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Sandbox) DeepCopy() *Sandbox {
	if in == nil {
		return nil
	}
	out := new(Sandbox)
	in.DeepCopyInto(out)
	return out
}

func (in *Sandbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SandboxList) DeepCopyInto(out *SandboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Sandbox, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SandboxList) DeepCopy() *SandboxList {
	if in == nil {
		return nil
	}
	out := new(SandboxList)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SandboxSpec) DeepCopyInto(out *SandboxSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.AllowedBinaries != nil {
		in, out := &in.AllowedBinaries, &out.AllowedBinaries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VM != nil {
		in, out := &in.VM, &out.VM
		*out = new(api.VMConfig)
		deepCopyVMConfig(*in, *out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(api.SandboxNetworkConfig)
		deepCopyNetworkConfig(*in, *out)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]api.VolumeMount, len(*in))
		copy(*out, *in)
	}
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]api.SandboxPatch, len(*in))
		copy(*out, *in)
	}
	if in.RetentionPeriod != nil {
		in, out := &in.RetentionPeriod, &out.RetentionPeriod
		*out = new(metav1.Duration)
		**out = **in
	}
}

func (in *SandboxSpec) DeepCopy() *SandboxSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxStatus) DeepCopyInto(out *SandboxStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.TerminatedAt != nil {
		in, out := &in.TerminatedAt, &out.TerminatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastExecAt != nil {
		in, out := &in.LastExecAt, &out.LastExecAt
		*out = (*in).DeepCopy()
	}
}

func (in *SandboxStatus) DeepCopy() *SandboxStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxStatus)
	in.DeepCopyInto(out)
	return out
}

func deepCopyVMConfig(in, out *api.VMConfig) {
	*out = *in
	if in.Rlimits != nil {
		out.Rlimits = make([]api.VMRlimit, len(in.Rlimits))
		copy(out.Rlimits, in.Rlimits)
	}
	if in.Scripts != nil {
		out.Scripts = make([]api.VMScript, len(in.Scripts))
		copy(out.Scripts, in.Scripts)
	}
}

func deepCopyNetworkConfig(in, out *api.SandboxNetworkConfig) {
	*out = *in
	if in.Enabled != nil {
		b := *in.Enabled
		out.Enabled = &b
	}
	if in.Rules != nil {
		out.Rules = make([]api.NetworkRule, len(in.Rules))
		for i := range in.Rules {
			r := in.Rules[i]
			if r.Protocols != nil {
				r.Protocols = make([]string, len(in.Rules[i].Protocols))
				copy(r.Protocols, in.Rules[i].Protocols)
			}
			if r.Ports != nil {
				r.Ports = make([]uint16, len(in.Rules[i].Ports))
				copy(r.Ports, in.Rules[i].Ports)
			}
			if r.PortRanges != nil {
				r.PortRanges = make([]api.PortRange, len(in.Rules[i].PortRanges))
				copy(r.PortRanges, in.Rules[i].PortRanges)
			}
			if r.Domains != nil {
				r.Domains = make([]string, len(in.Rules[i].Domains))
				copy(r.Domains, in.Rules[i].Domains)
			}
			if r.DomainSuffixes != nil {
				r.DomainSuffixes = make([]string, len(in.Rules[i].DomainSuffixes))
				copy(r.DomainSuffixes, in.Rules[i].DomainSuffixes)
			}
			if r.CIDRs != nil {
				r.CIDRs = make([]string, len(in.Rules[i].CIDRs))
				copy(r.CIDRs, in.Rules[i].CIDRs)
			}
			if r.Groups != nil {
				r.Groups = make([]string, len(in.Rules[i].Groups))
				copy(r.Groups, in.Rules[i].Groups)
			}
			out.Rules[i] = r
		}
	}
	if in.Ports != nil {
		out.Ports = make([]api.PortMapping, len(in.Ports))
		copy(out.Ports, in.Ports)
	}
	if in.DNS != nil {
		d := *in.DNS
		if in.DNS.Nameservers != nil {
			d.Nameservers = make([]string, len(in.DNS.Nameservers))
			copy(d.Nameservers, in.DNS.Nameservers)
		}
		if in.DNS.RebindProtection != nil {
			b := *in.DNS.RebindProtection
			d.RebindProtection = &b
		}
		out.DNS = &d
	}
	if in.Secrets != nil {
		out.Secrets = make([]api.NetworkSecret, len(in.Secrets))
		for i := range in.Secrets {
			s := in.Secrets[i]
			if s.AllowedHosts != nil {
				s.AllowedHosts = make([]string, len(in.Secrets[i].AllowedHosts))
				copy(s.AllowedHosts, in.Secrets[i].AllowedHosts)
			}
			if s.AllowedHostPatterns != nil {
				s.AllowedHostPatterns = make([]string, len(in.Secrets[i].AllowedHostPatterns))
				copy(s.AllowedHostPatterns, in.Secrets[i].AllowedHostPatterns)
			}
			out.Secrets[i] = s
		}
	}
}
