//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"

	"boxy.dev/boxy/internal/api"
)

func (in *Sandbox) DeepCopyInto(out *Sandbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *Sandbox) DeepCopy() *Sandbox {
	if in == nil {
		return nil
	}
	out := new(Sandbox)
	in.DeepCopyInto(out)
	return out
}

func (in *Sandbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SandboxList) DeepCopyInto(out *SandboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Sandbox, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SandboxList) DeepCopy() *SandboxList {
	if in == nil {
		return nil
	}
	out := new(SandboxList)
	in.DeepCopyInto(out)
	return out
}

func (in *SandboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SandboxSpec) DeepCopyInto(out *SandboxSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.AllowedBinaries != nil {
		in, out := &in.AllowedBinaries, &out.AllowedBinaries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VM != nil {
		in, out := &in.VM, &out.VM
		*out = new(api.VMConfig)
		deepCopyVMConfig(*in, *out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(api.SandboxNetworkConfig)
		deepCopyNetworkConfig(*in, *out)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]api.VolumeMount, len(*in))
		copy(*out, *in)
	}
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]api.SandboxPatch, len(*in))
		copy(*out, *in)
	}
	if in.ScriptEnv != nil {
		in, out := &in.ScriptEnv, &out.ScriptEnv
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

func (in *SandboxSpec) DeepCopy() *SandboxSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ControllerPool) DeepCopyInto(out *ControllerPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ControllerPool) DeepCopy() *ControllerPool {
	if in == nil {
		return nil
	}
	out := new(ControllerPool)
	in.DeepCopyInto(out)
	return out
}

func (in *ControllerPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ControllerPoolList) DeepCopyInto(out *ControllerPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControllerPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ControllerPoolList) DeepCopy() *ControllerPoolList {
	if in == nil {
		return nil
	}
	out := new(ControllerPoolList)
	in.DeepCopyInto(out)
	return out
}

func (in *ControllerPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ControllerPoolSpec) DeepCopyInto(out *ControllerPoolSpec) {
	*out = *in
	if in.PreinstalledBinaries != nil {
		in, out := &in.PreinstalledBinaries, &out.PreinstalledBinaries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ControllerPoolSpec) DeepCopy() *ControllerPoolSpec {
	if in == nil {
		return nil
	}
	out := new(ControllerPoolSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ControllerPoolStatus) DeepCopyInto(out *ControllerPoolStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ControllerPoolStatus) DeepCopy() *ControllerPoolStatus {
	if in == nil {
		return nil
	}
	out := new(ControllerPoolStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *Session) DeepCopyInto(out *Session) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Session) DeepCopy() *Session {
	if in == nil {
		return nil
	}
	out := new(Session)
	in.DeepCopyInto(out)
	return out
}

func (in *Session) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SessionList) DeepCopyInto(out *SessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Session, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SessionList) DeepCopy() *SessionList {
	if in == nil {
		return nil
	}
	out := new(SessionList)
	in.DeepCopyInto(out)
	return out
}

func (in *SessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SessionSpec) DeepCopyInto(out *SessionSpec) {
	*out = *in
}

func (in *SessionSpec) DeepCopy() *SessionSpec {
	if in == nil {
		return nil
	}
	out := new(SessionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SessionStatus) DeepCopyInto(out *SessionStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastExecAt != nil {
		in, out := &in.LastExecAt, &out.LastExecAt
		*out = (*in).DeepCopy()
	}
	if in.TerminatedAt != nil {
		in, out := &in.TerminatedAt, &out.TerminatedAt
		*out = (*in).DeepCopy()
	}
}

func (in *SessionStatus) DeepCopy() *SessionStatus {
	if in == nil {
		return nil
	}
	out := new(SessionStatus)
	in.DeepCopyInto(out)
	return out
}

func deepCopyVMConfig(in, out *api.VMConfig) {
	*out = *in
	if in.Rlimits != nil {
		out.Rlimits = make([]api.VMRlimit, len(in.Rlimits))
		copy(out.Rlimits, in.Rlimits)
	}
	if in.Scripts != nil {
		out.Scripts = make([]api.VMScript, len(in.Scripts))
		copy(out.Scripts, in.Scripts)
	}
}

func deepCopyNetworkConfig(in, out *api.SandboxNetworkConfig) {
	*out = *in
	if in.Enabled != nil {
		b := *in.Enabled
		out.Enabled = &b
	}
	if in.Macvlan != nil {
		mv := *in.Macvlan
		out.Macvlan = &mv
	}
}
